##########
#Created by: Sunny Jain
#Date: March 4th, 2021
#Last Modified: March 10th, 2021
#This is a spring-themed turtle program which will draw a ladybug, stars, flowers, and some text.


#initializations and imports
import turtle
import random
height = 400
width = 600
screen = turtle.getscreen()
screen.setup(width, height)
turtle.bgcolor("light cyan")
#turtle.tracer(0,0)

#The functions that I will be using
def star():
    colours = ["red", "medium blue", "green", "blue violet"]
    s = turtle.Turtle()
    s.penup()
    s.speed(1000)
    for x in range (0, random.randint(10, 15)):
        s.penup()
        coordinatex1 = (random.randint(-500,0))
        coordinatey = (random.randint(-300,300 ))
        s.goto(coordinatex1, coordinatey)
        s.pensize(3)
        s.pendown()
        s.color(random.choice(colours))
        for y in range(0, 3):
            s.pendown
            for z in range (2):
                s.right(90)
                for a in range (18):
                    s.fd(2)
                    s.rt(3)
        s.penup()
        coordinatex2 = (random.randint(0, 500))
        coordinatey = (random.randint(-300, 300))
        s.goto(coordinatex2, coordinatey)
        s.pensize(3)
        s.pendown()
        s.color(random.choice(colours))
        for y in range(0, 3):
            s.pendown
            for z in range (2):
                s.right(90)
                for a in range (18):
                    s.fd(2)
                    s.rt(3)


def flower():
    f = turtle.Turtle()
    f.penup()
    f.setposition(turtle.pos())
    f.penup()
    colours = ["tomato", "cyan", "green yellow", "yellow", "orange red", "lavender", "light pink"]
    colour = random.choice(colours)
    f.pen(pencolor = "black", fillcolor = colour)
    f.penup()
    f.shape("circle")
    f.shapesize(3, 3/2, 4)
    f.penup()
    f.stamp()
    f.penup()
    f.rt(90)
    f.fd(60)
    f.rt(90)
    f.stamp()
    f.rt(90)
    f.fd(30)
    f.rt(90)
    f.fd(30)
    f.rt(90)
    f.stamp()
    f.rt(90)
    f.fd(60)
    f.rt(90)
    f.stamp()
    f.fd(30)
    f.rt(45)
    f.stamp()
    f.rt(90)
    f.fd(85)
    f.rt(90)
    f.stamp()
    f.rt(45)
    f.fd(60)
    f.rt(45)
    f.stamp()
    f.rt(135)
    f.fd(60)
    f.rt(270)
    f.fd(60)
    f.rt(135)
    f.stamp()
    f.shape("circle")
    f.pen(pencolor = "black", fillcolor = "brown")
    f.penup()
    f.shapesize(5/2, 5/2, 4)
    f.rt(90)
    f.fd(42.5)
    f.stamp()
    f.penup()
    return(f)
    

def miniFlower():
    colours = ["midnight blue", "cyan", "spring green", "yellow", "orange red", "medium purple", "indigo"]
    mf = turtle.Turtle()
    mf.penup()
    mf.goto(turtle.pos())
    mf.pensize(8)
    mf.color(random.choice(colours))
    mf.fillcolor("saddle brown")
    mf.begin_fill()
    for y in range(0, 3):
            mf.pendown()
            for z in range (2):
                mf.right(90)
                for a in range (18):
                    mf.fd(2)
                    mf.rt(3)
    mf.end_fill()
    mf.penup()

#This is the main code: (don't forget to add the stars at the start)

star()
turtle.goto(0,0)
turtle.rt(90)
turtle.penup()
turtle.fd(425)
turtle.rt(90)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("green")
turtle.fd(500)
turtle.rt(90)
turtle.fd(200)
turtle.rt(90)
turtle.fd(1000)
turtle.rt(90)
turtle.fd(200)
turtle.rt(90)
turtle.fd(1000)
turtle.end_fill()
turtle.penup()
turtle.goto(0,0)
turtle.rt(270)
turtle.fd(300)
turtle.rt(90)
turtle.fd(500)
turtle.rt(180)
for x in range (0, 11):
    miniFlower()
    turtle.fd(101)
turtle.penup()
turtle.goto(0,0)
turtle.penup()
turtle.rt(90)
turtle.fd(200)
turtle.rt(90)
turtle.fd(500)
turtle.rt(180)
for y in range (0, 7):
    turtle.penup()
    flower()
    turtle.fd(165)

turtle.goto(0,-175)
turtle.pencolor("black")
turtle.pensize(5)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("red")
turtle.circle(200)
turtle.end_fill()
turtle.pencolor("black")
turtle.pensize(5)
turtle.goto(0,-175)
turtle.pendown()
turtle.rt(270)
turtle.fd(400)
print(turtle.pos())
turtle.rt(180)
turtle.fd(50)
turtle.rt(90)
turtle.penup()
turtle.fd(75)
turtle.dot(30)
turtle.rt(180)
turtle.fd(150)
turtle.dot(30)
turtle.rt(180)
turtle.fd(75)
turtle.rt(270)
turtle.fd(75)
turtle.rt(90)
turtle.fd(100)
turtle.dot(30)
turtle.rt(180)
turtle.fd(200)
turtle.dot(30)
print(turtle.pos())
turtle.goto(-150,25)
turtle.dot(30)
turtle.goto(-65, 25)
turtle.dot(30)
turtle.goto(65, 25)
turtle.dot(30)
turtle.goto(150, 25)
turtle.dot(30)
turtle.goto(-90, -50)
turtle.dot(30)
turtle.goto(90, -50)
turtle.dot(30)
turtle.goto(-50, -125)
turtle.dot(30)
turtle.goto(50, -125)
turtle.dot(30)
turtle.goto(0, 230)
turtle.begin_fill()
turtle.color("black")
turtle.shape("circle")
turtle.shapesize(5, 8, 4)
turtle.stamp()
turtle.goto(-40, 240)
turtle.color("white")
turtle.dot(30)
turtle.goto(40, 240)
turtle.dot(30)

#This concludes my drawing, now I will insert some text.
turtle.goto(-300, 200)
turtle.color("black")
turtle.write("S", font = ("comic Sans MS", 70, "normal"))
turtle.goto(-300, 120)
turtle.write("P", font = ("comic Sans MS", 70, "normal"))
turtle.goto(-300, 40)
turtle.write("R", font = ("comic Sans MS", 70, "normal"))
turtle.goto(-300, -40)
turtle.write("I", font = ("comic Sans MS", 70, "normal"))
turtle.goto(-300, -120)
turtle.write("N", font = ("comic Sans MS", 70, "normal"))
turtle.goto(-300, -200)
turtle.write("G", font = ("comic Sans MS", 70, "normal"))

turtle.goto(0,-0)
turtle.write("IS", align="center", font = ("comic Sans MS", 50, "normal"))

turtle.goto(250, 160)
turtle.write("H", font = ("comic Sans MS", 70, "normal"))
turtle.goto(250, 80)
turtle.write("E", font = ("comic Sans MS", 70, "normal"))
turtle.goto(250, 0)
turtle.write("R", font = ("comic Sans MS", 70, "normal"))
turtle.goto(250, -80)
turtle.write("E", font = ("comic Sans MS", 70, "normal"))
turtle.goto(250, -160)
turtle.write(" !", align="center", font = ("comic Sans MS", 70, "normal"))

turtle.shapesize(1,1,1)
turtle.goto(500,500)
